# Generated by Django 3.1.2 on 2020-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_title_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=40)),
                ('date_published', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
